


-- Chèn dữ liệu vào bảng city
INSERT INTO city (id, name, division_type, codename, phone_code) VALUES 
(1, 'Thành phố Hà Nội', 'tỉnh', 'thanh_pho_ha_noi', 24),
 (2, 'Tỉnh Hà Giang', 'tỉnh', 'tinh_ha_giang', 219),
 (4, 'Tỉnh Cao Bằng', 'tỉnh', 'tinh_cao_bang', 206),
 (6, 'Tỉnh Bắc Kạn', 'tỉnh', 'tinh_bac_kan', 209),
 (8, 'Tỉnh Tuyên Quang', 'tỉnh', 'tinh_tuyen_quang', 207),
 (10, 'Tỉnh Lào Cai', 'tỉnh', 'tinh_lao_cai', 214),
 (11, 'Tỉnh Điện Biên', 'tỉnh', 'tinh_dien_bien', 215),
 (12, 'Tỉnh Lai Châu', 'tỉnh', 'tinh_lai_chau', 213),
 (14, 'Tỉnh Sơn La', 'tỉnh', 'tinh_son_la', 212),
 (15, 'Tỉnh Yên Bái', 'tỉnh', 'tinh_yen_bai', 216),
 (17, 'Tỉnh Hoà Bình', 'tỉnh', 'tinh_hoa_binh', 218),
 (19, 'Tỉnh Thái Nguyên', 'tỉnh', 'tinh_thai_nguyen', 208),
 (20, 'Tỉnh Lạng Sơn', 'tỉnh', 'tinh_lang_son', 205),
 (22, 'Tỉnh Quảng Ninh', 'tỉnh', 'tinh_quang_ninh', 203),
 (24, 'Tỉnh Bắc Giang', 'tỉnh', 'tinh_bac_giang', 204),
 (25, 'Tỉnh Phú Thọ', 'tỉnh', 'tinh_phu_tho', 210),
 (26, 'Tỉnh Vĩnh Phúc', 'tỉnh', 'tinh_vinh_phuc', 211),
 (27, 'Tỉnh Bắc Ninh', 'tỉnh', 'tinh_bac_ninh', 222),
 (30, 'Tỉnh Hải Dương', 'tỉnh', 'tinh_hai_duong', 220),
 (31, 'Thành phố Hải Phòng', 'tỉnh', 'thanh_pho_hai_phong', 225),
 (33, 'Tỉnh Hưng Yên', 'tỉnh', 'tinh_hung_yen', 221),
 (34, 'Tỉnh Thái Bình', 'tỉnh', 'tinh_thai_binh', 227),
 (35, 'Tỉnh Hà Nam', 'tỉnh', 'tinh_ha_nam', 226),
 (36, 'Tỉnh Nam Định', 'tỉnh', 'tinh_nam_dinh', 228),
 (37, 'Tỉnh Ninh Bình', 'tỉnh', 'tinh_ninh_binh', 229),
 (38, 'Tỉnh Thanh Hóa', 'tỉnh', 'tinh_thanh_hoa', 237),
 (40, 'Tỉnh Nghệ An', 'tỉnh', 'tinh_nghe_an', 238),
 (42, 'Tỉnh Hà Tĩnh', 'tỉnh', 'tinh_ha_tinh', 239),
 (44, 'Tỉnh Quảng Bình', 'tỉnh', 'tinh_quang_binh', 232),
 (45, 'Tỉnh Quảng Trị', 'tỉnh', 'tinh_quang_tri', 233),
 (46, 'Thành phố Huế', 'tỉnh', 'thanh_pho_hue', 234),
 (48, 'Thành phố Đà Nẵng', 'tỉnh', 'thanh_pho_da_nang', 236),
 (49, 'Tỉnh Quảng Nam', 'tỉnh', 'tinh_quang_nam', 235),
 (51, 'Tỉnh Quảng Ngãi', 'tỉnh', 'tinh_quang_ngai', 255),
 (52, 'Tỉnh Bình Định', 'tỉnh', 'tinh_binh_dinh', 256),
 (54, 'Tỉnh Phú Yên', 'tỉnh', 'tinh_phu_yen', 257),
 (56, 'Tỉnh Khánh Hòa', 'tỉnh', 'tinh_khanh_hoa', 258),
 (58, 'Tỉnh Ninh Thuận', 'tỉnh', 'tinh_ninh_thuan', 259),
 (60, 'Tỉnh Bình Thuận', 'tỉnh', 'tinh_binh_thuan', 252),
 (62, 'Tỉnh Kon Tum', 'tỉnh', 'tinh_kon_tum', 260),
 (64, 'Tỉnh Gia Lai', 'tỉnh', 'tinh_gia_lai', 269),
 (66, 'Tỉnh Đắk Lắk', 'tỉnh', 'tinh_dak_lak', 262),
 (67, 'Tỉnh Đắk Nông', 'tỉnh', 'tinh_dak_nong', 261),
 (68, 'Tỉnh Lâm Đồng', 'tỉnh', 'tinh_lam_dong', 263),
 (70, 'Tỉnh Bình Phước', 'tỉnh', 'tinh_binh_phuoc', 271),
 (72, 'Tỉnh Tây Ninh', 'tỉnh', 'tinh_tay_ninh', 276),
 (74, 'Tỉnh Bình Dương', 'tỉnh', 'tinh_binh_duong', 274),
 (75, 'Tỉnh Đồng Nai', 'tỉnh', 'tinh_dong_nai', 251),
 (77, 'Tỉnh Bà Rịa - Vũng Tàu', 'tỉnh', 'tinh_ba_ria_vung_tau', 254),
 (79, 'Thành phố Hồ Chí Minh', 'tỉnh', 'thanh_pho_ho_chi_minh', 28),
 (80, 'Tỉnh Long An', 'tỉnh', 'tinh_long_an', 272),
 (82, 'Tỉnh Tiền Giang', 'tỉnh', 'tinh_tien_giang', 273),
 (83, 'Tỉnh Bến Tre', 'tỉnh', 'tinh_ben_tre', 275),
 (84, 'Tỉnh Trà Vinh', 'tỉnh', 'tinh_tra_vinh', 294),
 (86, 'Tỉnh Vĩnh Long', 'tỉnh', 'tinh_vinh_long', 270),
 (87, 'Tỉnh Đồng Tháp', 'tỉnh', 'tinh_dong_thap', 277),
 (89, 'Tỉnh An Giang', 'tỉnh', 'tinh_an_giang', 296),
 (91, 'Tỉnh Kiên Giang', 'tỉnh', 'tinh_kien_giang', 297),
 (92, 'Thành phố Cần Thơ', 'tỉnh', 'thanh_pho_can_tho', 292),
 (93, 'Tỉnh Hậu Giang', 'tỉnh', 'tinh_hau_giang', 293),
 (94, 'Tỉnh Sóc Trăng', 'tỉnh', 'tinh_soc_trang', 299),
 (95, 'Tỉnh Bạc Liêu', 'tỉnh', 'tinh_bac_lieu', 291),
 (96, 'Tỉnh Cà Mau', 'tỉnh', 'tinh_ca_mau', 290),

-- Chèn dữ liệu vào bảng districts
INSERT INTO districts (id, name, division_type, codename, city_id) VALUES 
(1, 'Quận Ba Đình', 'huyện', 'quan_ba_dinh', 1),
 (2, 'Quận Hoàn Kiếm', 'huyện', 'quan_hoan_kiem', 1),
 (3, 'Quận Tây Hồ', 'huyện', 'quan_tay_ho', 1),
 (4, 'Quận Long Biên', 'huyện', 'quan_long_bien', 1),
 (5, 'Quận Cầu Giấy', 'huyện', 'quan_cau_giay', 1),
 (6, 'Quận Đống Đa', 'huyện', 'quan_dong_da', 1),
 (7, 'Quận Hai Bà Trưng', 'huyện', 'quan_hai_ba_trung', 1),
 (8, 'Quận Hoàng Mai', 'huyện', 'quan_hoang_mai', 1),
 (9, 'Quận Thanh Xuân', 'huyện', 'quan_thanh_xuan', 1),
 (16, 'Huyện Sóc Sơn', 'huyện', 'huyen_soc_son', 1),
 (17, 'Huyện Đông Anh', 'huyện', 'huyen_dong_anh', 1),
 (18, 'Huyện Gia Lâm', 'huyện', 'huyen_gia_lam', 1),
 (19, 'Quận Nam Từ Liêm', 'huyện', 'quan_nam_tu_liem', 1),
 (20, 'Huyện Thanh Trì', 'huyện', 'huyen_thanh_tri', 1),
 (21, 'Quận Bắc Từ Liêm', 'huyện', 'quan_bac_tu_liem', 1),
 (250, 'Huyện Mê Linh', 'huyện', 'huyen_me_linh', 1),
 (268, 'Quận Hà Đông', 'huyện', 'quan_ha_dong', 1),
 (269, 'Thị xã Sơn Tây', 'huyện', 'thi_xa_son_tay', 1),
 (271, 'Huyện Ba Vì', 'huyện', 'huyen_ba_vi', 1),
 (272, 'Huyện Phúc Thọ', 'huyện', 'huyen_phuc_tho', 1),
 (273, 'Huyện Đan Phượng', 'huyện', 'huyen_dan_phuong', 1),
 (274, 'Huyện Hoài Đức', 'huyện', 'huyen_hoai_duc', 1),
 (275, 'Huyện Quốc Oai', 'huyện', 'huyen_quoc_oai', 1),
 (276, 'Huyện Thạch Thất', 'huyện', 'huyen_thach_that', 1),
 (277, 'Huyện Chương Mỹ', 'huyện', 'huyen_chuong_my', 1),
 (278, 'Huyện Thanh Oai', 'huyện', 'huyen_thanh_oai', 1),
 (279, 'Huyện Thường Tín', 'huyện', 'huyen_thuong_tin', 1),
 (280, 'Huyện Phú Xuyên', 'huyện', 'huyen_phu_xuyen', 1),
 (281, 'Huyện Ứng Hòa', 'huyện', 'huyen_ung_hoa', 1),
 (282, 'Huyện Mỹ Đức', 'huyện', 'huyen_my_duc', 1),
 (24, 'Thành phố Hà Giang', 'huyện', 'thanh_pho_ha_giang', 2),
 (26, 'Huyện Đồng Văn', 'huyện', 'huyen_dong_van', 2),
 (27, 'Huyện Mèo Vạc', 'huyện', 'huyen_meo_vac', 2),
 (28, 'Huyện Yên Minh', 'huyện', 'huyen_yen_minh', 2),
 (29, 'Huyện Quản Bạ', 'huyện', 'huyen_quan_ba', 2),
 (30, 'Huyện Vị Xuyên', 'huyện', 'huyen_vi_xuyen', 2),
 (31, 'Huyện Bắc Mê', 'huyện', 'huyen_bac_me', 2),
 (32, 'Huyện Hoàng Su Phì', 'huyện', 'huyen_hoang_su_phi', 2),
 (33, 'Huyện Xín Mần', 'huyện', 'huyen_xin_man', 2),
 (34, 'Huyện Bắc Quang', 'huyện', 'huyen_bac_quang', 2),
 (35, 'Huyện Quang Bình', 'huyện', 'huyen_quang_binh', 2),
 (40, 'Thành phố Cao Bằng', 'huyện', 'thanh_pho_cao_bang', 4),
 (42, 'Huyện Bảo Lâm', 'huyện', 'huyen_bao_lam', 4),
 (43, 'Huyện Bảo Lạc', 'huyện', 'huyen_bao_lac', 4),
 (45, 'Huyện Hà Quảng', 'huyện', 'huyen_ha_quang', 4),
 (47, 'Huyện Trùng Khánh', 'huyện', 'huyen_trung_khanh', 4),
 (48, 'Huyện Hạ Lang', 'huyện', 'huyen_ha_lang', 4),
 (49, 'Huyện Quảng Hòa', 'huyện', 'huyen_quang_hoa', 4),
 (51, 'Huyện Hoà An', 'huyện', 'huyen_hoa_an', 4),
 (52, 'Huyện Nguyên Bình', 'huyện', 'huyen_nguyen_binh', 4),
 (53, 'Huyện Thạch An', 'huyện', 'huyen_thach_an', 4),
 (58, 'Thành Phố Bắc Kạn', 'huyện', 'thanh_pho_bac_kan', 6),
 (60, 'Huyện Pác Nặm', 'huyện', 'huyen_pac_nam', 6),
 (61, 'Huyện Ba Bể', 'huyện', 'huyen_ba_be', 6),
 (62, 'Huyện Ngân Sơn', 'huyện', 'huyen_ngan_son', 6),
 (63, 'Huyện Bạch Thông', 'huyện', 'huyen_bach_thong', 6),
 (64, 'Huyện Chợ Đồn', 'huyện', 'huyen_cho_don', 6),
 (65, 'Huyện Chợ Mới', 'huyện', 'huyen_cho_moi', 6),
 (66, 'Huyện Na Rì', 'huyện', 'huyen_na_ri', 6),
 (70, 'Thành phố Tuyên Quang', 'huyện', 'thanh_pho_tuyen_quang', 8),
 (71, 'Huyện Lâm Bình', 'huyện', 'huyen_lam_binh', 8),
 (72, 'Huyện Na Hang', 'huyện', 'huyen_na_hang', 8),
 (73, 'Huyện Chiêm Hóa', 'huyện', 'huyen_chiem_hoa', 8),
 (74, 'Huyện Hàm Yên', 'huyện', 'huyen_ham_yen', 8),
 (75, 'Huyện Yên Sơn', 'huyện', 'huyen_yen_son', 8),
 (76, 'Huyện Sơn Dương', 'huyện', 'huyen_son_duong', 8),
 (80, 'Thành phố Lào Cai', 'huyện', 'thanh_pho_lao_cai', 10),
 (82, 'Huyện Bát Xát', 'huyện', 'huyen_bat_xat', 10),
 (83, 'Huyện Mường Khương', 'huyện', 'huyen_muong_khuong', 10),
 (84, 'Huyện Si Ma Cai', 'huyện', 'huyen_si_ma_cai', 10),
 (85, 'Huyện Bắc Hà', 'huyện', 'huyen_bac_ha', 10),
 (86, 'Huyện Bảo Thắng', 'huyện', 'huyen_bao_thang', 10),
 (87, 'Huyện Bảo Yên', 'huyện', 'huyen_bao_yen', 10),
 (88, 'Thị xã Sa Pa', 'huyện', 'thi_xa_sa_pa', 10),
 (89, 'Huyện Văn Bàn', 'huyện', 'huyen_van_ban', 10),
 (94, 'Thành phố Điện Biên Phủ', 'huyện', 'thanh_pho_dien_bien_phu', 11),
 (95, 'Thị xã Mường Lay', 'huyện', 'thi_xa_muong_lay', 11),
 (96, 'Huyện Mường Nhé', 'huyện', 'huyen_muong_nhe', 11),
 (97, 'Huyện Mường Chà', 'huyện', 'huyen_muong_cha', 11),
 (98, 'Huyện Tủa Chùa', 'huyện', 'huyen_tua_chua', 11),
 (99, 'Huyện Tuần Giáo', 'huyện', 'huyen_tuan_giao', 11),
 (100, 'Huyện Điện Biên', 'huyện', 'huyen_dien_bien', 11),
 (101, 'Huyện Điện Biên Đông', 'huyện', 'huyen_dien_bien_dong', 11),
 (102, 'Huyện Mường Ảng', 'huyện', 'huyen_muong_ang', 11),
 (103, 'Huyện Nậm Pồ', 'huyện', 'huyen_nam_po', 11),
 (105, 'Thành phố Lai Châu', 'huyện', 'thanh_pho_lai_chau', 12),
 (106, 'Huyện Tam Đường', 'huyện', 'huyen_tam_duong', 12),
 (107, 'Huyện Mường Tè', 'huyện', 'huyen_muong_te', 12),
 (108, 'Huyện Sìn Hồ', 'huyện', 'huyen_sin_ho', 12),
 (109, 'Huyện Phong Thổ', 'huyện', 'huyen_phong_tho', 12),
 (110, 'Huyện Than Uyên', 'huyện', 'huyen_than_uyen', 12),
 (111, 'Huyện Tân Uyên', 'huyện', 'huyen_tan_uyen', 12),
 (112, 'Huyện Nậm Nhùn', 'huyện', 'huyen_nam_nhun', 12),
 (116, 'Thành phố Sơn La', 'huyện', 'thanh_pho_son_la', 14),
 (118, 'Huyện Quỳnh Nhai', 'huyện', 'huyen_quynh_nhai', 14),
 (119, 'Huyện Thuận Châu', 'huyện', 'huyen_thuan_chau', 14),
 (120, 'Huyện Mường La', 'huyện', 'huyen_muong_la', 14),
 (121, 'Huyện Bắc Yên', 'huyện', 'huyen_bac_yen', 14),
 (122, 'Huyện Phù Yên', 'huyện', 'huyen_phu_yen', 14),
 (123, 'Huyện Mộc Châu', 'huyện', 'huyen_moc_chau', 14),
 (124, 'Huyện Yên Châu', 'huyện', 'huyen_yen_chau', 14),
 (125, 'Huyện Mai Sơn', 'huyện', 'huyen_mai_son', 14),
 (126, 'Huyện Sông Mã', 'huyện', 'huyen_song_ma', 14),
 (127, 'Huyện Sốp Cộp', 'huyện', 'huyen_sop_cop', 14),
 (128, 'Huyện Vân Hồ', 'huyện', 'huyen_van_ho', 14),
 (132, 'Thành phố Yên Bái', 'huyện', 'thanh_pho_yen_bai', 15),
 (133, 'Thị xã Nghĩa Lộ', 'huyện', 'thi_xa_nghia_lo', 15),
 (135, 'Huyện Lục Yên', 'huyện', 'huyen_luc_yen', 15),
 (136, 'Huyện Văn Yên', 'huyện', 'huyen_van_yen', 15),
 (137, 'Huyện Mù Căng Chải', 'huyện', 'huyen_mu_cang_chai', 15),
 (138, 'Huyện Trấn Yên', 'huyện', 'huyen_tran_yen', 15),
 (139, 'Huyện Trạm Tấu', 'huyện', 'huyen_tram_tau', 15),
 (140, 'Huyện Văn Chấn', 'huyện', 'huyen_van_chan', 15),
 (141, 'Huyện Yên Bình', 'huyện', 'huyen_yen_binh', 15),
 (148, 'Thành phố Hòa Bình', 'huyện', 'thanh_pho_hoa_binh', 17),
 (150, 'Huyện Đà Bắc', 'huyện', 'huyen_da_bac', 17),
 (152, 'Huyện Lương Sơn', 'huyện', 'huyen_luong_son', 17),
 (153, 'Huyện Kim Bôi', 'huyện', 'huyen_kim_boi', 17),
 (154, 'Huyện Cao Phong', 'huyện', 'huyen_cao_phong', 17),
 (155, 'Huyện Tân Lạc', 'huyện', 'huyen_tan_lac', 17),
 (156, 'Huyện Mai Châu', 'huyện', 'huyen_mai_chau', 17),
 (157, 'Huyện Lạc Sơn', 'huyện', 'huyen_lac_son', 17),
 (158, 'Huyện Yên Thủy', 'huyện', 'huyen_yen_thuy', 17),
 (159, 'Huyện Lạc Thủy', 'huyện', 'huyen_lac_thuy', 17),
 (164, 'Thành phố Thái Nguyên', 'huyện', 'thanh_pho_thai_nguyen', 19),
 (165, 'Thành phố Sông Công', 'huyện', 'thanh_pho_song_cong', 19),
 (167, 'Huyện Định Hóa', 'huyện', 'huyen_dinh_hoa', 19),
 (168, 'Huyện Phú Lương', 'huyện', 'huyen_phu_luong', 19),
 (169, 'Huyện Đồng Hỷ', 'huyện', 'huyen_dong_hy', 19),
 (170, 'Huyện Võ Nhai', 'huyện', 'huyen_vo_nhai', 19),
 (171, 'Huyện Đại Từ', 'huyện', 'huyen_dai_tu', 19),
 (172, 'Thành phố Phổ Yên', 'huyện', 'thanh_pho_pho_yen', 19),
 (173, 'Huyện Phú Bình', 'huyện', 'huyen_phu_binh', 19),
 (178, 'Thành phố Lạng Sơn', 'huyện', 'thanh_pho_lang_son', 20),
 (180, 'Huyện Tràng Định', 'huyện', 'huyen_trang_dinh', 20),
 (181, 'Huyện Bình Gia', 'huyện', 'huyen_binh_gia', 20),
 (182, 'Huyện Văn Lãng', 'huyện', 'huyen_van_lang', 20),
 (183, 'Huyện Cao Lộc', 'huyện', 'huyen_cao_loc', 20),
 (184, 'Huyện Văn Quan', 'huyện', 'huyen_van_quan', 20),
 (185, 'Huyện Bắc Sơn', 'huyện', 'huyen_bac_son', 20),
 (186, 'Huyện Hữu Lũng', 'huyện', 'huyen_huu_lung', 20),
 (187, 'Huyện Chi Lăng', 'huyện', 'huyen_chi_lang', 20),
 (188, 'Huyện Lộc Bình', 'huyện', 'huyen_loc_binh', 20),
 (189, 'Huyện Đình Lập', 'huyện', 'huyen_dinh_lap', 20),
 (193, 'Thành phố Hạ Long', 'huyện', 'thanh_pho_ha_long', 22),
 (194, 'Thành phố Móng Cái', 'huyện', 'thanh_pho_mong_cai', 22),
 (195, 'Thành phố Cẩm Phả', 'huyện', 'thanh_pho_cam_pha', 22),
 (196, 'Thành phố Uông Bí', 'huyện', 'thanh_pho_uong_bi', 22),
 (198, 'Huyện Bình Liêu', 'huyện', 'huyen_binh_lieu', 22),
 (199, 'Huyện Tiên Yên', 'huyện', 'huyen_tien_yen', 22),
 (200, 'Huyện Đầm Hà', 'huyện', 'huyen_dam_ha', 22),
 (201, 'Huyện Hải Hà', 'huyện', 'huyen_hai_ha', 22),
 (202, 'Huyện Ba Chẽ', 'huyện', 'huyen_ba_che', 22),
 (203, 'Huyện Vân Đồn', 'huyện', 'huyen_van_don', 22),
 (205, 'Thành phố Đông Triều', 'huyện', 'thanh_pho_dong_trieu', 22),
 (206, 'Thị xã Quảng Yên', 'huyện', 'thi_xa_quang_yen', 22),
 (207, 'Huyện Cô Tô', 'huyện', 'huyen_co_to', 22),
 (213, 'Thành phố Bắc Giang', 'huyện', 'thanh_pho_bac_giang', 24),
 (215, 'Huyện Yên Thế', 'huyện', 'huyen_yen_the', 24),
 (216, 'Huyện Tân Yên', 'huyện', 'huyen_tan_yen', 24),
 (217, 'Huyện Lạng Giang', 'huyện', 'huyen_lang_giang', 24),
 (218, 'Huyện Lục Nam', 'huyện', 'huyen_luc_nam', 24),
 (219, 'Huyện Lục Ngạn', 'huyện', 'huyen_luc_ngan', 24),
 (220, 'Huyện Sơn Động', 'huyện', 'huyen_son_dong', 24),
 (222, 'Thị xã Việt Yên', 'huyện', 'thi_xa_viet_yen', 24),
 (223, 'Huyện Hiệp Hòa', 'huyện', 'huyen_hiep_hoa', 24),
 (224, 'Thị xã Chũ', 'huyện', 'thi_xa_chu', 24),
 (227, 'Thành phố Việt Trì', 'huyện', 'thanh_pho_viet_tri', 25),
 (228, 'Thị xã Phú Thọ', 'huyện', 'thi_xa_phu_tho', 25),
 (230, 'Huyện Đoan Hùng', 'huyện', 'huyen_doan_hung', 25),
 (231, 'Huyện Hạ Hoà', 'huyện', 'huyen_ha_hoa', 25),
 (232, 'Huyện Thanh Ba', 'huyện', 'huyen_thanh_ba', 25),
 (233, 'Huyện Phù Ninh', 'huyện', 'huyen_phu_ninh', 25),
 (234, 'Huyện Yên Lập', 'huyện', 'huyen_yen_lap', 25),
 (235, 'Huyện Cẩm Khê', 'huyện', 'huyen_cam_khe', 25),
 (236, 'Huyện Tam Nông', 'huyện', 'huyen_tam_nong', 25),
 (237, 'Huyện Lâm Thao', 'huyện', 'huyen_lam_thao', 25),
 (238, 'Huyện Thanh Sơn', 'huyện', 'huyen_thanh_son', 25),
 (239, 'Huyện Thanh Thuỷ', 'huyện', 'huyen_thanh_thuy', 25),
 (240, 'Huyện Tân Sơn', 'huyện', 'huyen_tan_son', 25),
 (243, 'Thành phố Vĩnh Yên', 'huyện', 'thanh_pho_vinh_yen', 26),
 (244, 'Thành phố Phúc Yên', 'huyện', 'thanh_pho_phuc_yen', 26),
 (246, 'Huyện Lập Thạch', 'huyện', 'huyen_lap_thach', 26),
 (247, 'Huyện Tam Dương', 'huyện', 'huyen_tam_duong', 26),
 (248, 'Huyện Tam Đảo', 'huyện', 'huyen_tam_dao', 26),
 (249, 'Huyện Bình Xuyên', 'huyện', 'huyen_binh_xuyen', 26),
 (251, 'Huyện Yên Lạc', 'huyện', 'huyen_yen_lac', 26),
 (252, 'Huyện Vĩnh Tường', 'huyện', 'huyen_vinh_tuong', 26),
 (253, 'Huyện Sông Lô', 'huyện', 'huyen_song_lo', 26),
 (256, 'Thành phố Bắc Ninh', 'huyện', 'thanh_pho_bac_ninh', 27),
 (258, 'Huyện Yên Phong', 'huyện', 'huyen_yen_phong', 27),
 (259, 'Thị xã Quế Võ', 'huyện', 'thi_xa_que_vo', 27),
 (260, 'Huyện Tiên Du', 'huyện', 'huyen_tien_du', 27),
 (261, 'Thành phố Từ Sơn', 'huyện', 'thanh_pho_tu_son', 27),
 (262, 'Thị xã Thuận Thành', 'huyện', 'thi_xa_thuan_thanh', 27),
 (263, 'Huyện Gia Bình', 'huyện', 'huyen_gia_binh', 27),
 (264, 'Huyện Lương Tài', 'huyện', 'huyen_luong_tai', 27),
 (288, 'Thành phố Hải Dương', 'huyện', 'thanh_pho_hai_duong', 30),
 (290, 'Thành phố Chí Linh', 'huyện', 'thanh_pho_chi_linh', 30),
 (291, 'Huyện Nam Sách', 'huyện', 'huyen_nam_sach', 30),
 (292, 'Thị xã Kinh Môn', 'huyện', 'thi_xa_kinh_mon', 30),
 (293, 'Huyện Kim Thành', 'huyện', 'huyen_kim_thanh', 30),
 (294, 'Huyện Thanh Hà', 'huyện', 'huyen_thanh_ha', 30),
 (295, 'Huyện Cẩm Giàng', 'huyện', 'huyen_cam_giang', 30),
 (296, 'Huyện Bình Giang', 'huyện', 'huyen_binh_giang', 30),
 (297, 'Huyện Gia Lộc', 'huyện', 'huyen_gia_loc', 30),
 (298, 'Huyện Tứ Kỳ', 'huyện', 'huyen_tu_ky', 30),
 (299, 'Huyện Ninh Giang', 'huyện', 'huyen_ninh_giang', 30),
 (300, 'Huyện Thanh Miện', 'huyện', 'huyen_thanh_mien', 30),
 (303, 'Quận Hồng Bàng', 'huyện', 'quan_hong_bang', 31),
 (304, 'Quận Ngô Quyền', 'huyện', 'quan_ngo_quyen', 31),
 (305, 'Quận Lê Chân', 'huyện', 'quan_le_chan', 31),
 (306, 'Quận Hải An', 'huyện', 'quan_hai_an', 31),
 (307, 'Quận Kiến An', 'huyện', 'quan_kien_an', 31),
 (308, 'Quận Đồ Sơn', 'huyện', 'quan_do_son', 31),
 (309, 'Quận Dương Kinh', 'huyện', 'quan_duong_kinh', 31),
 (311, 'Thành phố Thuỷ Nguyên', 'huyện', 'thanh_pho_thuy_nguyen', 31),
 (312, 'Quận An Dương', 'huyện', 'quan_an_duong', 31),
 (313, 'Huyện An Lão', 'huyện', 'huyen_an_lao', 31),
 (314, 'Huyện Kiến Thuỵ', 'huyện', 'huyen_kien_thuy', 31),
 (315, 'Huyện Tiên Lãng', 'huyện', 'huyen_tien_lang', 31),
 (316, 'Huyện Vĩnh Bảo', 'huyện', 'huyen_vinh_bao', 31),
 (317, 'Huyện Cát Hải', 'huyện', 'huyen_cat_hai', 31),
 (323, 'Thành phố Hưng Yên', 'huyện', 'thanh_pho_hung_yen', 33),
 (325, 'Huyện Văn Lâm', 'huyện', 'huyen_van_lam', 33),
 (326, 'Huyện Văn Giang', 'huyện', 'huyen_van_giang', 33),
 (327, 'Huyện Yên Mỹ', 'huyện', 'huyen_yen_my', 33),
 (328, 'Thị xã Mỹ Hào', 'huyện', 'thi_xa_my_hao', 33),
 (329, 'Huyện Ân Thi', 'huyện', 'huyen_an_thi', 33),
 (330, 'Huyện Khoái Châu', 'huyện', 'huyen_khoai_chau', 33),
 (331, 'Huyện Kim Động', 'huyện', 'huyen_kim_dong', 33),
 (332, 'Huyện Tiên Lữ', 'huyện', 'huyen_tien_lu', 33),
 (333, 'Huyện Phù Cừ', 'huyện', 'huyen_phu_cu', 33),
 (336, 'Thành phố Thái Bình', 'huyện', 'thanh_pho_thai_binh', 34),
 (338, 'Huyện Quỳnh Phụ', 'huyện', 'huyen_quynh_phu', 34),
 (339, 'Huyện Hưng Hà', 'huyện', 'huyen_hung_ha', 34),
 (340, 'Huyện Đông Hưng', 'huyện', 'huyen_dong_hung', 34),
 (341, 'Huyện Thái Thụy', 'huyện', 'huyen_thai_thuy', 34),
 (342, 'Huyện Tiền Hải', 'huyện', 'huyen_tien_hai', 34),
 (343, 'Huyện Kiến Xương', 'huyện', 'huyen_kien_xuong', 34),
 (344, 'Huyện Vũ Thư', 'huyện', 'huyen_vu_thu', 34),
 (347, 'Thành phố Phủ Lý', 'huyện', 'thanh_pho_phu_ly', 35),
 (349, 'Thị xã Duy Tiên', 'huyện', 'thi_xa_duy_tien', 35),
 (350, 'Thị xã Kim Bảng', 'huyện', 'thi_xa_kim_bang', 35),
 (351, 'Huyện Thanh Liêm', 'huyện', 'huyen_thanh_liem', 35),
 (352, 'Huyện Bình Lục', 'huyện', 'huyen_binh_luc', 35),
 (353, 'Huyện Lý Nhân', 'huyện', 'huyen_ly_nhan', 35),
 (356, 'Thành phố Nam Định', 'huyện', 'thanh_pho_nam_dinh', 36),
 (359, 'Huyện Vụ Bản', 'huyện', 'huyen_vu_ban', 36),
 (360, 'Huyện Ý Yên', 'huyện', 'huyen_y_yen', 36),
 (361, 'Huyện Nghĩa Hưng', 'huyện', 'huyen_nghia_hung', 36),
 (362, 'Huyện Nam Trực', 'huyện', 'huyen_nam_truc', 36),
 (363, 'Huyện Trực Ninh', 'huyện', 'huyen_truc_ninh', 36),
 (364, 'Huyện Xuân Trường', 'huyện', 'huyen_xuan_truong', 36),
 (365, 'Huyện Giao Thủy', 'huyện', 'huyen_giao_thuy', 36),
 (366, 'Huyện Hải Hậu', 'huyện', 'huyen_hai_hau', 36),
 (370, 'Thành phố Tam Điệp', 'huyện', 'thanh_pho_tam_diep', 37),
 (372, 'Huyện Nho Quan', 'huyện', 'huyen_nho_quan', 37),
 (373, 'Huyện Gia Viễn', 'huyện', 'huyen_gia_vien', 37),
 (374, 'Thành phố Hoa Lư', 'huyện', 'thanh_pho_hoa_lu', 37),
 (375, 'Huyện Yên Khánh', 'huyện', 'huyen_yen_khanh', 37),
 (376, 'Huyện Kim Sơn', 'huyện', 'huyen_kim_son', 37),
 (377, 'Huyện Yên Mô', 'huyện', 'huyen_yen_mo', 37),
 (380, 'Thành phố Thanh Hóa', 'huyện', 'thanh_pho_thanh_hoa', 38),
 (381, 'Thị xã Bỉm Sơn', 'huyện', 'thi_xa_bim_son', 38),
 (382, 'Thành phố Sầm Sơn', 'huyện', 'thanh_pho_sam_son', 38),
 (384, 'Huyện Mường Lát', 'huyện', 'huyen_muong_lat', 38),
 (385, 'Huyện Quan Hóa', 'huyện', 'huyen_quan_hoa', 38),
 (386, 'Huyện Bá Thước', 'huyện', 'huyen_ba_thuoc', 38),
 (387, 'Huyện Quan Sơn', 'huyện', 'huyen_quan_son', 38),
 (388, 'Huyện Lang Chánh', 'huyện', 'huyen_lang_chanh', 38),
 (389, 'Huyện Ngọc Lặc', 'huyện', 'huyen_ngoc_lac', 38),
 (390, 'Huyện Cẩm Thủy', 'huyện', 'huyen_cam_thuy', 38),
 (391, 'Huyện Thạch Thành', 'huyện', 'huyen_thach_thanh', 38),
 (392, 'Huyện Hà Trung', 'huyện', 'huyen_ha_trung', 38),
 (393, 'Huyện Vĩnh Lộc', 'huyện', 'huyen_vinh_loc', 38),
 (394, 'Huyện Yên Định', 'huyện', 'huyen_yen_dinh', 38),
 (395, 'Huyện Thọ Xuân', 'huyện', 'huyen_tho_xuan', 38),
 (396, 'Huyện Thường Xuân', 'huyện', 'huyen_thuong_xuan', 38),
 (397, 'Huyện Triệu Sơn', 'huyện', 'huyen_trieu_son', 38),
 (398, 'Huyện Thiệu Hóa', 'huyện', 'huyen_thieu_hoa', 38),
 (399, 'Huyện Hoằng Hóa', 'huyện', 'huyen_hoang_hoa', 38),
 (400, 'Huyện Hậu Lộc', 'huyện', 'huyen_hau_loc', 38),
 (401, 'Huyện Nga Sơn', 'huyện', 'huyen_nga_son', 38),
 (402, 'Huyện Như Xuân', 'huyện', 'huyen_nhu_xuan', 38),
 (403, 'Huyện Như Thanh', 'huyện', 'huyen_nhu_thanh', 38),
 (404, 'Huyện Nông Cống', 'huyện', 'huyen_nong_cong', 38),
 (406, 'Huyện Quảng Xương', 'huyện', 'huyen_quang_xuong', 38),
 (407, 'Thị xã Nghi Sơn', 'huyện', 'thi_xa_nghi_son', 38),
 (412, 'Thành phố Vinh', 'huyện', 'thanh_pho_vinh', 40),
 (414, 'Thị xã Thái Hoà', 'huyện', 'thi_xa_thai_hoa', 40),
 (415, 'Huyện Quế Phong', 'huyện', 'huyen_que_phong', 40),
 (416, 'Huyện Quỳ Châu', 'huyện', 'huyen_quy_chau', 40),
 (417, 'Huyện Kỳ Sơn', 'huyện', 'huyen_ky_son', 40),
 (418, 'Huyện Tương Dương', 'huyện', 'huyen_tuong_duong', 40),
 (419, 'Huyện Nghĩa Đàn', 'huyện', 'huyen_nghia_dan', 40),
 (420, 'Huyện Quỳ Hợp', 'huyện', 'huyen_quy_hop', 40),
 (421, 'Huyện Quỳnh Lưu', 'huyện', 'huyen_quynh_luu', 40),
 (422, 'Huyện Con Cuông', 'huyện', 'huyen_con_cuong', 40),
 (423, 'Huyện Tân Kỳ', 'huyện', 'huyen_tan_ky', 40),
 (424, 'Huyện Anh Sơn', 'huyện', 'huyen_anh_son', 40),
 (425, 'Huyện Diễn Châu', 'huyện', 'huyen_dien_chau', 40),
 (426, 'Huyện Yên Thành', 'huyện', 'huyen_yen_thanh', 40),
 (427, 'Huyện Đô Lương', 'huyện', 'huyen_do_luong', 40),
 (428, 'Huyện Thanh Chương', 'huyện', 'huyen_thanh_chuong', 40),
 (429, 'Huyện Nghi Lộc', 'huyện', 'huyen_nghi_loc', 40),
 (430, 'Huyện Nam Đàn', 'huyện', 'huyen_nam_dan', 40),
 (431, 'Huyện Hưng Nguyên', 'huyện', 'huyen_hung_nguyen', 40),
 (432, 'Thị xã Hoàng Mai', 'huyện', 'thi_xa_hoang_mai', 40),
 (436, 'Thành phố Hà Tĩnh', 'huyện', 'thanh_pho_ha_tinh', 42),
 (437, 'Thị xã Hồng Lĩnh', 'huyện', 'thi_xa_hong_linh', 42),
 (439, 'Huyện Hương Sơn', 'huyện', 'huyen_huong_son', 42),
 (440, 'Huyện Đức Thọ', 'huyện', 'huyen_duc_tho', 42),
 (441, 'Huyện Vũ Quang', 'huyện', 'huyen_vu_quang', 42),
 (442, 'Huyện Nghi Xuân', 'huyện', 'huyen_nghi_xuan', 42),
 (443, 'Huyện Can Lộc', 'huyện', 'huyen_can_loc', 42),
 (444, 'Huyện Hương Khê', 'huyện', 'huyen_huong_khe', 42),
 (445, 'Huyện Thạch Hà', 'huyện', 'huyen_thach_ha', 42),
 (446, 'Huyện Cẩm Xuyên', 'huyện', 'huyen_cam_xuyen', 42),
 (447, 'Huyện Kỳ Anh', 'huyện', 'huyen_ky_anh', 42),
 (449, 'Thị xã Kỳ Anh', 'huyện', 'thi_xa_ky_anh', 42),
 (450, 'Thành Phố Đồng Hới', 'huyện', 'thanh_pho_dong_hoi', 44),
 (452, 'Huyện Minh Hóa', 'huyện', 'huyen_minh_hoa', 44),
 (453, 'Huyện Tuyên Hóa', 'huyện', 'huyen_tuyen_hoa', 44),
 (454, 'Huyện Quảng Trạch', 'huyện', 'huyen_quang_trach', 44),
 (455, 'Huyện Bố Trạch', 'huyện', 'huyen_bo_trach', 44),
 (456, 'Huyện Quảng Ninh', 'huyện', 'huyen_quang_ninh', 44),
 (457, 'Huyện Lệ Thủy', 'huyện', 'huyen_le_thuy', 44),
 (458, 'Thị xã Ba Đồn', 'huyện', 'thi_xa_ba_don', 44),
 (461, 'Thành phố Đông Hà', 'huyện', 'thanh_pho_dong_ha', 45),
 (462, 'Thị xã Quảng Trị', 'huyện', 'thi_xa_quang_tri', 45),
 (464, 'Huyện Vĩnh Linh', 'huyện', 'huyen_vinh_linh', 45),
 (465, 'Huyện Hướng Hóa', 'huyện', 'huyen_huong_hoa', 45),
 (466, 'Huyện Gio Linh', 'huyện', 'huyen_gio_linh', 45),
 (467, 'Huyện Đa Krông', 'huyện', 'huyen_da_krong', 45),
 (468, 'Huyện Cam Lộ', 'huyện', 'huyen_cam_lo', 45),
 (469, 'Huyện Triệu Phong', 'huyện', 'huyen_trieu_phong', 45),
 (470, 'Huyện Hải Lăng', 'huyện', 'huyen_hai_lang', 45),
 (474, 'Quận Thuận Hóa', 'huyện', 'quan_thuan_hoa', 46),
 (475, 'Quận Phú Xuân', 'huyện', 'quan_phu_xuan', 46),
 (476, 'Thị xã Phong Điền', 'huyện', 'thi_xa_phong_dien', 46),
 (477, 'Huyện Quảng Điền', 'huyện', 'huyen_quang_dien', 46),
 (478, 'Huyện Phú Vang', 'huyện', 'huyen_phu_vang', 46),
 (479, 'Thị xã Hương Thủy', 'huyện', 'thi_xa_huong_thuy', 46),
 (480, 'Thị xã Hương Trà', 'huyện', 'thi_xa_huong_tra', 46),
 (481, 'Huyện A Lưới', 'huyện', 'huyen_a_luoi', 46),
 (482, 'Huyện Phú Lộc', 'huyện', 'huyen_phu_loc', 46),
 (490, 'Quận Liên Chiểu', 'huyện', 'quan_lien_chieu', 48),
 (491, 'Quận Thanh Khê', 'huyện', 'quan_thanh_khe', 48),
 (492, 'Quận Hải Châu', 'huyện', 'quan_hai_chau', 48),
 (493, 'Quận Sơn Trà', 'huyện', 'quan_son_tra', 48),
 (494, 'Quận Ngũ Hành Sơn', 'huyện', 'quan_ngu_hanh_son', 48),
 (495, 'Quận Cẩm Lệ', 'huyện', 'quan_cam_le', 48),
 (497, 'Huyện Hòa Vang', 'huyện', 'huyen_hoa_vang', 48),
 (502, 'Thành phố Tam Kỳ', 'huyện', 'thanh_pho_tam_ky', 49),
 (503, 'Thành phố Hội An', 'huyện', 'thanh_pho_hoi_an', 49),
 (504, 'Huyện Tây Giang', 'huyện', 'huyen_tay_giang', 49),
 (505, 'Huyện Đông Giang', 'huyện', 'huyen_dong_giang', 49),
 (506, 'Huyện Đại Lộc', 'huyện', 'huyen_dai_loc', 49),
 (507, 'Thị xã Điện Bàn', 'huyện', 'thi_xa_dien_ban', 49),
 (508, 'Huyện Duy Xuyên', 'huyện', 'huyen_duy_xuyen', 49),
 (509, 'Huyện Quế Sơn', 'huyện', 'huyen_que_son', 49),
 (510, 'Huyện Nam Giang', 'huyện', 'huyen_nam_giang', 49),
 (511, 'Huyện Phước Sơn', 'huyện', 'huyen_phuoc_son', 49),
 (512, 'Huyện Hiệp Đức', 'huyện', 'huyen_hiep_duc', 49),
 (513, 'Huyện Thăng Bình', 'huyện', 'huyen_thang_binh', 49),
 (514, 'Huyện Tiên Phước', 'huyện', 'huyen_tien_phuoc', 49),
 (515, 'Huyện Bắc Trà My', 'huyện', 'huyen_bac_tra_my', 49),
 (516, 'Huyện Nam Trà My', 'huyện', 'huyen_nam_tra_my', 49),
 (517, 'Huyện Núi Thành', 'huyện', 'huyen_nui_thanh', 49),
 (518, 'Huyện Phú Ninh', 'huyện', 'huyen_phu_ninh', 49),
 (522, 'Thành phố Quảng Ngãi', 'huyện', 'thanh_pho_quang_ngai', 51),
 (524, 'Huyện Bình Sơn', 'huyện', 'huyen_binh_son', 51),
 (525, 'Huyện Trà Bồng', 'huyện', 'huyen_tra_bong', 51),
 (527, 'Huyện Sơn Tịnh', 'huyện', 'huyen_son_tinh', 51),
 (528, 'Huyện Tư Nghĩa', 'huyện', 'huyen_tu_nghia', 51),
 (529, 'Huyện Sơn Hà', 'huyện', 'huyen_son_ha', 51),
 (530, 'Huyện Sơn Tây', 'huyện', 'huyen_son_tay', 51),
 (531, 'Huyện Minh Long', 'huyện', 'huyen_minh_long', 51),
 (532, 'Huyện Nghĩa Hành', 'huyện', 'huyen_nghia_hanh', 51),
 (533, 'Huyện Mộ Đức', 'huyện', 'huyen_mo_duc', 51),
 (534, 'Thị xã Đức Phổ', 'huyện', 'thi_xa_duc_pho', 51),
 (535, 'Huyện Ba Tơ', 'huyện', 'huyen_ba_to', 51),
 (540, 'Thành phố Quy Nhơn', 'huyện', 'thanh_pho_quy_nhon', 52),
 (542, 'Huyện An Lão', 'huyện', 'huyen_an_lao', 52),
 (543, 'Thị xã Hoài Nhơn', 'huyện', 'thi_xa_hoai_nhon', 52),
 (544, 'Huyện Hoài Ân', 'huyện', 'huyen_hoai_an', 52),
 (545, 'Huyện Phù Mỹ', 'huyện', 'huyen_phu_my', 52),
 (546, 'Huyện Vĩnh Thạnh', 'huyện', 'huyen_vinh_thanh', 52),
 (547, 'Huyện Tây Sơn', 'huyện', 'huyen_tay_son', 52),
 (548, 'Huyện Phù Cát', 'huyện', 'huyen_phu_cat', 52),
 (549, 'Thị xã An Nhơn', 'huyện', 'thi_xa_an_nhon', 52),
 (550, 'Huyện Tuy Phước', 'huyện', 'huyen_tuy_phuoc', 52),
 (551, 'Huyện Vân Canh', 'huyện', 'huyen_van_canh', 52),
 (555, 'Thành phố Tuy Hoà', 'huyện', 'thanh_pho_tuy_hoa', 54),
 (557, 'Thị xã Sông Cầu', 'huyện', 'thi_xa_song_cau', 54),
 (558, 'Huyện Đồng Xuân', 'huyện', 'huyen_dong_xuan', 54),
 (559, 'Huyện Tuy An', 'huyện', 'huyen_tuy_an', 54),
 (560, 'Huyện Sơn Hòa', 'huyện', 'huyen_son_hoa', 54),
 (561, 'Huyện Sông Hinh', 'huyện', 'huyen_song_hinh', 54),
 (562, 'Huyện Tây Hoà', 'huyện', 'huyen_tay_hoa', 54),
 (563, 'Huyện Phú Hoà', 'huyện', 'huyen_phu_hoa', 54),
 (564, 'Thị xã Đông Hòa', 'huyện', 'thi_xa_dong_hoa', 54),
 (568, 'Thành phố Nha Trang', 'huyện', 'thanh_pho_nha_trang', 56),
 (569, 'Thành phố Cam Ranh', 'huyện', 'thanh_pho_cam_ranh', 56),
 (570, 'Huyện Cam Lâm', 'huyện', 'huyen_cam_lam', 56),
 (571, 'Huyện Vạn Ninh', 'huyện', 'huyen_van_ninh', 56),
 (572, 'Thị xã Ninh Hòa', 'huyện', 'thi_xa_ninh_hoa', 56),
 (573, 'Huyện Khánh Vĩnh', 'huyện', 'huyen_khanh_vinh', 56),
 (574, 'Huyện Diên Khánh', 'huyện', 'huyen_dien_khanh', 56),
 (575, 'Huyện Khánh Sơn', 'huyện', 'huyen_khanh_son', 56),
 (576, 'Huyện Trường Sa', 'huyện', 'huyen_truong_sa', 56),
 (582, 'Thành phố Phan Rang-Tháp Chàm', 'huyện', 'thanh_pho_phan_rang_thap_cham', 58),
 (584, 'Huyện Bác Ái', 'huyện', 'huyen_bac_ai', 58),
 (585, 'Huyện Ninh Sơn', 'huyện', 'huyen_ninh_son', 58),
 (586, 'Huyện Ninh Hải', 'huyện', 'huyen_ninh_hai', 58),
 (587, 'Huyện Ninh Phước', 'huyện', 'huyen_ninh_phuoc', 58),
 (588, 'Huyện Thuận Bắc', 'huyện', 'huyen_thuan_bac', 58),
 (589, 'Huyện Thuận Nam', 'huyện', 'huyen_thuan_nam', 58),
 (593, 'Thành phố Phan Thiết', 'huyện', 'thanh_pho_phan_thiet', 60),
 (594, 'Thị xã La Gi', 'huyện', 'thi_xa_la_gi', 60),
 (595, 'Huyện Tuy Phong', 'huyện', 'huyen_tuy_phong', 60),
 (596, 'Huyện Bắc Bình', 'huyện', 'huyen_bac_binh', 60),
 (597, 'Huyện Hàm Thuận Bắc', 'huyện', 'huyen_ham_thuan_bac', 60),
 (598, 'Huyện Hàm Thuận Nam', 'huyện', 'huyen_ham_thuan_nam', 60),
 (599, 'Huyện Tánh Linh', 'huyện', 'huyen_tanh_linh', 60),
 (600, 'Huyện Đức Linh', 'huyện', 'huyen_duc_linh', 60),
 (601, 'Huyện Hàm Tân', 'huyện', 'huyen_ham_tan', 60),
 (602, 'Huyện Phú Quí', 'huyện', 'huyen_phu_qui', 60),
 (608, 'Thành phố Kon Tum', 'huyện', 'thanh_pho_kon_tum', 62),
 (610, 'Huyện Đắk Glei', 'huyện', 'huyen_dak_glei', 62),
 (611, 'Huyện Ngọc Hồi', 'huyện', 'huyen_ngoc_hoi', 62),
 (612, 'Huyện Đắk Tô', 'huyện', 'huyen_dak_to', 62),
 (613, 'Huyện Kon Plông', 'huyện', 'huyen_kon_plong', 62),
 (614, 'Huyện Kon Rẫy', 'huyện', 'huyen_kon_ray', 62),
 (615, 'Huyện Đắk Hà', 'huyện', 'huyen_dak_ha', 62),
 (616, 'Huyện Sa Thầy', 'huyện', 'huyen_sa_thay', 62),
 (617, 'Huyện Tu Mơ Rông', 'huyện', 'huyen_tu_mo_rong', 62),
 (618, 'Huyện Ia H'' Drai', 'huyện', 'huyen_ia_h_drai', 62),
 (622, 'Thành phố Pleiku', 'huyện', 'thanh_pho_pleiku', 64),
 (623, 'Thị xã An Khê', 'huyện', 'thi_xa_an_khe', 64),
 (624, 'Thị xã Ayun Pa', 'huyện', 'thi_xa_ayun_pa', 64),
 (625, 'Huyện KBang', 'huyện', 'huyen_kbang', 64),
 (626, 'Huyện Đăk Đoa', 'huyện', 'huyen_dak_doa', 64),
 (627, 'Huyện Chư Păh', 'huyện', 'huyen_chu_pah', 64),
 (628, 'Huyện Ia Grai', 'huyện', 'huyen_ia_grai', 64),
 (629, 'Huyện Mang Yang', 'huyện', 'huyen_mang_yang', 64),
 (630, 'Huyện Kông Chro', 'huyện', 'huyen_kong_chro', 64),
 (631, 'Huyện Đức Cơ', 'huyện', 'huyen_duc_co', 64),
 (632, 'Huyện Chư Prông', 'huyện', 'huyen_chu_prong', 64),
 (633, 'Huyện Chư Sê', 'huyện', 'huyen_chu_se', 64),
 (634, 'Huyện Đăk Pơ', 'huyện', 'huyen_dak_po', 64),
 (635, 'Huyện Ia Pa', 'huyện', 'huyen_ia_pa', 64),
 (637, 'Huyện Krông Pa', 'huyện', 'huyen_krong_pa', 64),
 (638, 'Huyện Phú Thiện', 'huyện', 'huyen_phu_thien', 64),
 (639, 'Huyện Chư Pưh', 'huyện', 'huyen_chu_puh', 64),
 (643, 'Thành phố Buôn Ma Thuột', 'huyện', 'thanh_pho_buon_ma_thuot', 66),
 (644, 'Thị xã Buôn Hồ', 'huyện', 'thi_xa_buon_ho', 66),
 (645, 'Huyện Ea H''leo', 'huyện', 'huyen_ea_hleo', 66),
 (646, 'Huyện Ea Súp', 'huyện', 'huyen_ea_sup', 66),
 (647, 'Huyện Buôn Đôn', 'huyện', 'huyen_buon_don', 66),
 (648, 'Huyện Cư M''gar', 'huyện', 'huyen_cu_mgar', 66),
 (649, 'Huyện Krông Búk', 'huyện', 'huyen_krong_buk', 66),
 (650, 'Huyện Krông Năng', 'huyện', 'huyen_krong_nang', 66),
 (651, 'Huyện Ea Kar', 'huyện', 'huyen_ea_kar', 66),
 (652, 'Huyện M''Đrắk', 'huyện', 'huyen_mdrak', 66),
 (653, 'Huyện Krông Bông', 'huyện', 'huyen_krong_bong', 66),
 (654, 'Huyện Krông Pắc', 'huyện', 'huyen_krong_pac', 66),
 (655, 'Huyện Krông A Na', 'huyện', 'huyen_krong_a_na', 66),
 (656, 'Huyện Lắk', 'huyện', 'huyen_lak', 66),
 (657, 'Huyện Cư Kuin', 'huyện', 'huyen_cu_kuin', 66),
 (660, 'Thành phố Gia Nghĩa', 'huyện', 'thanh_pho_gia_nghia', 67),
 (661, 'Huyện Đăk Glong', 'huyện', 'huyen_dak_glong', 67),
 (662, 'Huyện Cư Jút', 'huyện', 'huyen_cu_jut', 67),
 (663, 'Huyện Đắk Mil', 'huyện', 'huyen_dak_mil', 67),
 (664, 'Huyện Krông Nô', 'huyện', 'huyen_krong_no', 67),
 (665, 'Huyện Đắk Song', 'huyện', 'huyen_dak_song', 67),
 (666, 'Huyện Đắk R''Lấp', 'huyện', 'huyen_dak_rlap', 67),
 (667, 'Huyện Tuy Đức', 'huyện', 'huyen_tuy_duc', 67),
 (672, 'Thành phố Đà Lạt', 'huyện', 'thanh_pho_da_lat', 68),
 (673, 'Thành phố Bảo Lộc', 'huyện', 'thanh_pho_bao_loc', 68),
 (674, 'Huyện Đam Rông', 'huyện', 'huyen_dam_rong', 68),
 (675, 'Huyện Lạc Dương', 'huyện', 'huyen_lac_duong', 68),
 (676, 'Huyện Lâm Hà', 'huyện', 'huyen_lam_ha', 68),
 (677, 'Huyện Đơn Dương', 'huyện', 'huyen_don_duong', 68),
 (678, 'Huyện Đức Trọng', 'huyện', 'huyen_duc_trong', 68),
 (679, 'Huyện Di Linh', 'huyện', 'huyen_di_linh', 68),
 (680, 'Huyện Bảo Lâm', 'huyện', 'huyen_bao_lam', 68),
 (682, 'Huyện Đạ Huoai', 'huyện', 'huyen_da_huoai', 68),
 (688, 'Thị xã Phước Long', 'huyện', 'thi_xa_phuoc_long', 70),
 (689, 'Thành phố Đồng Xoài', 'huyện', 'thanh_pho_dong_xoai', 70),
 (690, 'Thị xã Bình Long', 'huyện', 'thi_xa_binh_long', 70),
 (691, 'Huyện Bù Gia Mập', 'huyện', 'huyen_bu_gia_map', 70),
 (692, 'Huyện Lộc Ninh', 'huyện', 'huyen_loc_ninh', 70),
 (693, 'Huyện Bù Đốp', 'huyện', 'huyen_bu_dop', 70),
 (694, 'Huyện Hớn Quản', 'huyện', 'huyen_hon_quan', 70),
 (695, 'Huyện Đồng Phú', 'huyện', 'huyen_dong_phu', 70),
 (696, 'Huyện Bù Đăng', 'huyện', 'huyen_bu_dang', 70),
 (697, 'Thị xã Chơn Thành', 'huyện', 'thi_xa_chon_thanh', 70),
 (698, 'Huyện Phú Riềng', 'huyện', 'huyen_phu_rieng', 70),
 (703, 'Thành phố Tây Ninh', 'huyện', 'thanh_pho_tay_ninh', 72),
 (705, 'Huyện Tân Biên', 'huyện', 'huyen_tan_bien', 72),
 (706, 'Huyện Tân Châu', 'huyện', 'huyen_tan_chau', 72),
 (707, 'Huyện Dương Minh Châu', 'huyện', 'huyen_duong_minh_chau', 72),
 (708, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 72),
 (709, 'Thị xã Hòa Thành', 'huyện', 'thi_xa_hoa_thanh', 72),
 (710, 'Huyện Gò Dầu', 'huyện', 'huyen_go_dau', 72),
 (711, 'Huyện Bến Cầu', 'huyện', 'huyen_ben_cau', 72),
 (712, 'Thị xã Trảng Bàng', 'huyện', 'thi_xa_trang_bang', 72),
 (718, 'Thành phố Thủ Dầu Một', 'huyện', 'thanh_pho_thu_dau_mot', 74),
 (719, 'Huyện Bàu Bàng', 'huyện', 'huyen_bau_bang', 74),
 (720, 'Huyện Dầu Tiếng', 'huyện', 'huyen_dau_tieng', 74),
 (721, 'Thành phố Bến Cát', 'huyện', 'thanh_pho_ben_cat', 74),
 (722, 'Huyện Phú Giáo', 'huyện', 'huyen_phu_giao', 74),
 (723, 'Thành phố Tân Uyên', 'huyện', 'thanh_pho_tan_uyen', 74),
 (724, 'Thành phố Dĩ An', 'huyện', 'thanh_pho_di_an', 74),
 (725, 'Thành phố Thuận An', 'huyện', 'thanh_pho_thuan_an', 74),
 (726, 'Huyện Bắc Tân Uyên', 'huyện', 'huyen_bac_tan_uyen', 74),
 (731, 'Thành phố Biên Hòa', 'huyện', 'thanh_pho_bien_hoa', 75),
 (732, 'Thành phố Long Khánh', 'huyện', 'thanh_pho_long_khanh', 75),
 (734, 'Huyện Tân Phú', 'huyện', 'huyen_tan_phu', 75),
 (735, 'Huyện Vĩnh Cửu', 'huyện', 'huyen_vinh_cuu', 75),
 (736, 'Huyện Định Quán', 'huyện', 'huyen_dinh_quan', 75),
 (737, 'Huyện Trảng Bom', 'huyện', 'huyen_trang_bom', 75),
 (738, 'Huyện Thống Nhất', 'huyện', 'huyen_thong_nhat', 75),
 (739, 'Huyện Cẩm Mỹ', 'huyện', 'huyen_cam_my', 75),
 (740, 'Huyện Long Thành', 'huyện', 'huyen_long_thanh', 75),
 (741, 'Huyện Xuân Lộc', 'huyện', 'huyen_xuan_loc', 75),
 (742, 'Huyện Nhơn Trạch', 'huyện', 'huyen_nhon_trach', 75),
 (747, 'Thành phố Vũng Tàu', 'huyện', 'thanh_pho_vung_tau', 77),
 (748, 'Thành phố Bà Rịa', 'huyện', 'thanh_pho_ba_ria', 77),
 (750, 'Huyện Châu Đức', 'huyện', 'huyen_chau_duc', 77),
 (751, 'Huyện Xuyên Mộc', 'huyện', 'huyen_xuyen_moc', 77),
 (753, 'Huyện Long Đất', 'huyện', 'huyen_long_dat', 77),
 (754, 'Thị xã Phú Mỹ', 'huyện', 'thi_xa_phu_my', 77),
 (760, 'Quận 1', 'huyện', 'quan_1', 79),
 (761, 'Quận 12', 'huyện', 'quan_12', 79),
 (764, 'Quận Gò Vấp', 'huyện', 'quan_go_vap', 79),
 (765, 'Quận Bình Thạnh', 'huyện', 'quan_binh_thanh', 79),
 (766, 'Quận Tân Bình', 'huyện', 'quan_tan_binh', 79),
 (767, 'Quận Tân Phú', 'huyện', 'quan_tan_phu', 79),
 (768, 'Quận Phú Nhuận', 'huyện', 'quan_phu_nhuan', 79),
 (769, 'Thành phố Thủ Đức', 'huyện', 'thanh_pho_thu_duc', 79),
 (770, 'Quận 3', 'huyện', 'quan_3', 79),
 (771, 'Quận 10', 'huyện', 'quan_10', 79),
 (772, 'Quận 11', 'huyện', 'quan_11', 79),
 (773, 'Quận 4', 'huyện', 'quan_4', 79),
 (774, 'Quận 5', 'huyện', 'quan_5', 79),
 (775, 'Quận 6', 'huyện', 'quan_6', 79),
 (776, 'Quận 8', 'huyện', 'quan_8', 79),
 (777, 'Quận Bình Tân', 'huyện', 'quan_binh_tan', 79),
 (778, 'Quận 7', 'huyện', 'quan_7', 79),
 (783, 'Huyện Củ Chi', 'huyện', 'huyen_cu_chi', 79),
 (784, 'Huyện Hóc Môn', 'huyện', 'huyen_hoc_mon', 79),
 (785, 'Huyện Bình Chánh', 'huyện', 'huyen_binh_chanh', 79),
 (786, 'Huyện Nhà Bè', 'huyện', 'huyen_nha_be', 79),
 (787, 'Huyện Cần Giờ', 'huyện', 'huyen_can_gio', 79),
 (794, 'Thành phố Tân An', 'huyện', 'thanh_pho_tan_an', 80),
 (795, 'Thị xã Kiến Tường', 'huyện', 'thi_xa_kien_tuong', 80),
 (796, 'Huyện Tân Hưng', 'huyện', 'huyen_tan_hung', 80),
 (797, 'Huyện Vĩnh Hưng', 'huyện', 'huyen_vinh_hung', 80),
 (798, 'Huyện Mộc Hóa', 'huyện', 'huyen_moc_hoa', 80),
 (799, 'Huyện Tân Thạnh', 'huyện', 'huyen_tan_thanh', 80),
 (800, 'Huyện Thạnh Hóa', 'huyện', 'huyen_thanh_hoa', 80),
 (801, 'Huyện Đức Huệ', 'huyện', 'huyen_duc_hue', 80),
 (802, 'Huyện Đức Hòa', 'huyện', 'huyen_duc_hoa', 80),
 (803, 'Huyện Bến Lức', 'huyện', 'huyen_ben_luc', 80),
 (804, 'Huyện Thủ Thừa', 'huyện', 'huyen_thu_thua', 80),
 (805, 'Huyện Tân Trụ', 'huyện', 'huyen_tan_tru', 80),
 (806, 'Huyện Cần Đước', 'huyện', 'huyen_can_duoc', 80),
 (807, 'Huyện Cần Giuộc', 'huyện', 'huyen_can_giuoc', 80),
 (808, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 80),
 (815, 'Thành phố Mỹ Tho', 'huyện', 'thanh_pho_my_tho', 82),
 (816, 'Thành phố Gò Công', 'huyện', 'thanh_pho_go_cong', 82),
 (817, 'Thị xã Cai Lậy', 'huyện', 'thi_xa_cai_lay', 82),
 (818, 'Huyện Tân Phước', 'huyện', 'huyen_tan_phuoc', 82),
 (819, 'Huyện Cái Bè', 'huyện', 'huyen_cai_be', 82),
 (820, 'Huyện Cai Lậy', 'huyện', 'huyen_cai_lay', 82),
 (821, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 82),
 (822, 'Huyện Chợ Gạo', 'huyện', 'huyen_cho_gao', 82),
 (823, 'Huyện Gò Công Tây', 'huyện', 'huyen_go_cong_tay', 82),
 (824, 'Huyện Gò Công Đông', 'huyện', 'huyen_go_cong_dong', 82),
 (825, 'Huyện Tân Phú Đông', 'huyện', 'huyen_tan_phu_dong', 82),
 (829, 'Thành phố Bến Tre', 'huyện', 'thanh_pho_ben_tre', 83),
 (831, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 83),
 (832, 'Huyện Chợ Lách', 'huyện', 'huyen_cho_lach', 83),
 (833, 'Huyện Mỏ Cày Nam', 'huyện', 'huyen_mo_cay_nam', 83),
 (834, 'Huyện Giồng Trôm', 'huyện', 'huyen_giong_trom', 83),
 (835, 'Huyện Bình Đại', 'huyện', 'huyen_binh_dai', 83),
 (836, 'Huyện Ba Tri', 'huyện', 'huyen_ba_tri', 83),
 (837, 'Huyện Thạnh Phú', 'huyện', 'huyen_thanh_phu', 83),
 (838, 'Huyện Mỏ Cày Bắc', 'huyện', 'huyen_mo_cay_bac', 83),
 (842, 'Thành phố Trà Vinh', 'huyện', 'thanh_pho_tra_vinh', 84),
 (844, 'Huyện Càng Long', 'huyện', 'huyen_cang_long', 84),
 (845, 'Huyện Cầu Kè', 'huyện', 'huyen_cau_ke', 84),
 (846, 'Huyện Tiểu Cần', 'huyện', 'huyen_tieu_can', 84),
 (847, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 84),
 (848, 'Huyện Cầu Ngang', 'huyện', 'huyen_cau_ngang', 84),
 (849, 'Huyện Trà Cú', 'huyện', 'huyen_tra_cu', 84),
 (850, 'Huyện Duyên Hải', 'huyện', 'huyen_duyen_hai', 84),
 (851, 'Thị xã Duyên Hải', 'huyện', 'thi_xa_duyen_hai', 84),
 (855, 'Thành phố Vĩnh Long', 'huyện', 'thanh_pho_vinh_long', 86),
 (857, 'Huyện Long Hồ', 'huyện', 'huyen_long_ho', 86),
 (858, 'Huyện Mang Thít', 'huyện', 'huyen_mang_thit', 86),
 (859, 'Huyện Vũng Liêm', 'huyện', 'huyen_vung_liem', 86),
 (860, 'Huyện Tam Bình', 'huyện', 'huyen_tam_binh', 86),
 (861, 'Thị xã Bình Minh', 'huyện', 'thi_xa_binh_minh', 86),
 (862, 'Huyện Trà Ôn', 'huyện', 'huyen_tra_on', 86),
 (863, 'Huyện Bình Tân', 'huyện', 'huyen_binh_tan', 86),
 (866, 'Thành phố Cao Lãnh', 'huyện', 'thanh_pho_cao_lanh', 87),
 (867, 'Thành phố Sa Đéc', 'huyện', 'thanh_pho_sa_dec', 87),
 (868, 'Thành phố Hồng Ngự', 'huyện', 'thanh_pho_hong_ngu', 87),
 (869, 'Huyện Tân Hồng', 'huyện', 'huyen_tan_hong', 87),
 (870, 'Huyện Hồng Ngự', 'huyện', 'huyen_hong_ngu', 87),
 (871, 'Huyện Tam Nông', 'huyện', 'huyen_tam_nong', 87),
 (872, 'Huyện Tháp Mười', 'huyện', 'huyen_thap_muoi', 87),
 (873, 'Huyện Cao Lãnh', 'huyện', 'huyen_cao_lanh', 87),
 (874, 'Huyện Thanh Bình', 'huyện', 'huyen_thanh_binh', 87),
 (875, 'Huyện Lấp Vò', 'huyện', 'huyen_lap_vo', 87),
 (876, 'Huyện Lai Vung', 'huyện', 'huyen_lai_vung', 87),
 (877, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 87),
 (883, 'Thành phố Long Xuyên', 'huyện', 'thanh_pho_long_xuyen', 89),
 (884, 'Thành phố Châu Đốc', 'huyện', 'thanh_pho_chau_doc', 89),
 (886, 'Huyện An Phú', 'huyện', 'huyen_an_phu', 89),
 (887, 'Thị xã Tân Châu', 'huyện', 'thi_xa_tan_chau', 89),
 (888, 'Huyện Phú Tân', 'huyện', 'huyen_phu_tan', 89),
 (889, 'Huyện Châu Phú', 'huyện', 'huyen_chau_phu', 89),
 (890, 'Thị xã Tịnh Biên', 'huyện', 'thi_xa_tinh_bien', 89),
 (891, 'Huyện Tri Tôn', 'huyện', 'huyen_tri_ton', 89),
 (892, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 89),
 (893, 'Huyện Chợ Mới', 'huyện', 'huyen_cho_moi', 89),
 (894, 'Huyện Thoại Sơn', 'huyện', 'huyen_thoai_son', 89),
 (899, 'Thành phố Rạch Giá', 'huyện', 'thanh_pho_rach_gia', 91),
 (900, 'Thành phố Hà Tiên', 'huyện', 'thanh_pho_ha_tien', 91),
 (902, 'Huyện Kiên Lương', 'huyện', 'huyen_kien_luong', 91),
 (903, 'Huyện Hòn Đất', 'huyện', 'huyen_hon_dat', 91),
 (904, 'Huyện Tân Hiệp', 'huyện', 'huyen_tan_hiep', 91),
 (905, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 91),
 (906, 'Huyện Giồng Riềng', 'huyện', 'huyen_giong_rieng', 91),
 (907, 'Huyện Gò Quao', 'huyện', 'huyen_go_quao', 91),
 (908, 'Huyện An Biên', 'huyện', 'huyen_an_bien', 91),
 (909, 'Huyện An Minh', 'huyện', 'huyen_an_minh', 91),
 (910, 'Huyện Vĩnh Thuận', 'huyện', 'huyen_vinh_thuan', 91),
 (911, 'Thành phố Phú Quốc', 'huyện', 'thanh_pho_phu_quoc', 91),
 (912, 'Huyện Kiên Hải', 'huyện', 'huyen_kien_hai', 91),
 (913, 'Huyện U Minh Thượng', 'huyện', 'huyen_u_minh_thuong', 91),
 (914, 'Huyện Giang Thành', 'huyện', 'huyen_giang_thanh', 91),
 (916, 'Quận Ninh Kiều', 'huyện', 'quan_ninh_kieu', 92),
 (917, 'Quận Ô Môn', 'huyện', 'quan_o_mon', 92),
 (918, 'Quận Bình Thuỷ', 'huyện', 'quan_binh_thuy', 92),
 (919, 'Quận Cái Răng', 'huyện', 'quan_cai_rang', 92),
 (923, 'Quận Thốt Nốt', 'huyện', 'quan_thot_not', 92),
 (924, 'Huyện Vĩnh Thạnh', 'huyện', 'huyen_vinh_thanh', 92),
 (925, 'Huyện Cờ Đỏ', 'huyện', 'huyen_co_do', 92),
 (926, 'Huyện Phong Điền', 'huyện', 'huyen_phong_dien', 92),
 (927, 'Huyện Thới Lai', 'huyện', 'huyen_thoi_lai', 92),
 (930, 'Thành phố Vị Thanh', 'huyện', 'thanh_pho_vi_thanh', 93),
 (931, 'Thành phố Ngã Bảy', 'huyện', 'thanh_pho_nga_bay', 93),
 (932, 'Huyện Châu Thành A', 'huyện', 'huyen_chau_thanh_a', 93),
 (933, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 93),
 (934, 'Huyện Phụng Hiệp', 'huyện', 'huyen_phung_hiep', 93),
 (935, 'Huyện Vị Thuỷ', 'huyện', 'huyen_vi_thuy', 93),
 (936, 'Huyện Long Mỹ', 'huyện', 'huyen_long_my', 93),
 (937, 'Thị xã Long Mỹ', 'huyện', 'thi_xa_long_my', 93),
 (941, 'Thành phố Sóc Trăng', 'huyện', 'thanh_pho_soc_trang', 94),
 (942, 'Huyện Châu Thành', 'huyện', 'huyen_chau_thanh', 94),
 (943, 'Huyện Kế Sách', 'huyện', 'huyen_ke_sach', 94),
 (944, 'Huyện Mỹ Tú', 'huyện', 'huyen_my_tu', 94),
 (945, 'Huyện Cù Lao Dung', 'huyện', 'huyen_cu_lao_dung', 94),
 (946, 'Huyện Long Phú', 'huyện', 'huyen_long_phu', 94),
 (947, 'Huyện Mỹ Xuyên', 'huyện', 'huyen_my_xuyen', 94),
 (948, 'Thị xã Ngã Năm', 'huyện', 'thi_xa_nga_nam', 94),
 (949, 'Huyện Thạnh Trị', 'huyện', 'huyen_thanh_tri', 94),
 (950, 'Thị xã Vĩnh Châu', 'huyện', 'thi_xa_vinh_chau', 94),
 (951, 'Huyện Trần Đề', 'huyện', 'huyen_tran_de', 94),
 (954, 'Thành phố Bạc Liêu', 'huyện', 'thanh_pho_bac_lieu', 95),
 (956, 'Huyện Hồng Dân', 'huyện', 'huyen_hong_dan', 95),
 (957, 'Huyện Phước Long', 'huyện', 'huyen_phuoc_long', 95),
 (958, 'Huyện Vĩnh Lợi', 'huyện', 'huyen_vinh_loi', 95),
 (959, 'Thị xã Giá Rai', 'huyện', 'thi_xa_gia_rai', 95),
 (960, 'Huyện Đông Hải', 'huyện', 'huyen_dong_hai', 95),
 (961, 'Huyện Hoà Bình', 'huyện', 'huyen_hoa_binh', 95),
 (964, 'Thành phố Cà Mau', 'huyện', 'thanh_pho_ca_mau', 96),
 (966, 'Huyện U Minh', 'huyện', 'huyen_u_minh', 96),
 (967, 'Huyện Thới Bình', 'huyện', 'huyen_thoi_binh', 96),
 (968, 'Huyện Trần Văn Thời', 'huyện', 'huyen_tran_van_thoi', 96),
 (969, 'Huyện Cái Nước', 'huyện', 'huyen_cai_nuoc', 96),
 (970, 'Huyện Đầm Dơi', 'huyện', 'huyen_dam_doi', 96),
 (971, 'Huyện Năm Căn', 'huyện', 'huyen_nam_can', 96),
 (972, 'Huyện Phú Tân', 'huyện', 'huyen_phu_tan', 96),
 (973, 'Huyện Ngọc Hiển', 'huyện', 'huyen_ngoc_hien', 96);