server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: AppMusic
  datasource:
    url: "jdbc:mysql://mainline.proxy.rlwy.net:17183/railway"
    username: root
    password: bczcLXvgbkeKwVGxgTBGkrJZChDsTjAK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  SECRET_KEY: "4Ln6h2KQDuYGyThDGPrZZ2MvBcmlrCpL5p3XlGWa/Qn0W1t/2GYGb+aEcw4wy8SP"
